[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:conduit]
command=/usr/local/bin/conduit
environment=CONDUIT_CONFIG="/etc/conduit/conduit.toml"
autostart=true
autorestart=true
stdout_logfile=/tmp/conduit.log
stderr_logfile=/tmp/conduit-error.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/tmp/nginx-supervisor.log
stderr_logfile=/tmp/nginx-supervisor-error.log
